on:
  workflow_dispatch:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Conda skeleton publish
    steps:
      - name: Publish conda package from PyPI package
        uses: actions/conda-skeleton-publish@v1
        with:
          pypi_package: "driptorch"
          python_version: "3.10 3.11"
          upload_channel: "conda-forge"
          access_token: ${{ secrets.ANACONDA_TOKEN }}
          stable: true
